// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include "ui_page_Mic1.h"
#include "string.h"
#include "stdio.h"
#include "ui_pmanager.h"
#include "my_i2c_driver.h"
static Mic1ObjsContext *ObjsCt;
static Mic1ArgsContext ArgsCt;
static uint8_t args_initialized;




// event funtions

// build funtions

void ui_page_Mic1_init(lv_obj_t *screen)
{
    {
        ObjsCt = (Mic1ObjsContext *)lv_mem_alloc(sizeof(Mic1ObjsContext));
        memset(ObjsCt, 0, sizeof(Mic1ObjsContext));
        if(!args_initialized)
        {
            memset(&ArgsCt, 0, sizeof(Mic1ArgsContext));
            ArgsCt.focus_target = 0;
            ArgsCt.edit_mode = 0;
            ArgsCt.gain_args = 0;      
            ArgsCt.phantom_args = 0;   
            ArgsCt.fx_args = 0;        
            ArgsCt.hi_args = 15;       
            ArgsCt.mid_args = 15;      
            ArgsCt.low_args = 15;      
            ArgsCt.hpf_args = 1;       
            ArgsCt.fbe_args = 1;       
            ArgsCt.pan_args = 0;       
            args_initialized = 1;
        }
    }

    ObjsCt->Mic1_obj = lv_img_create(screen);
    lv_obj_set_size(ObjsCt->Mic1_obj, 480, 320);
    lv_obj_set_style_bg_color(ObjsCt->Mic1_obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->Mic1_obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ObjsCt->Mic1_obj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ObjsCt->ui_select_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_select_panel, 200);
    lv_obj_set_height(ObjsCt->ui_select_panel, 62);
    lv_obj_set_x(ObjsCt->ui_select_panel, 15);
    lv_obj_set_y(ObjsCt->ui_select_panel, 2);
    lv_obj_clear_flag(ObjsCt->ui_select_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_select_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_select_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_select_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_select_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_select_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_select_name = lv_label_create(ObjsCt->ui_select_panel);
    lv_obj_set_width(ObjsCt->ui_select_name, 200);
    lv_obj_set_height(ObjsCt->ui_select_name, 31);
    lv_obj_set_align(ObjsCt->ui_select_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_select_name, "SELECTS");
    lv_obj_set_style_text_color(ObjsCt->ui_select_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_select_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_select_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_select_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_select_args = lv_label_create(ObjsCt->ui_select_panel);
    lv_obj_set_width(ObjsCt->ui_select_args, 200);
    lv_obj_set_height(ObjsCt->ui_select_args, 31);
    lv_obj_set_align(ObjsCt->ui_select_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_select_args, "1");
    lv_obj_set_style_text_color(ObjsCt->ui_select_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_select_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_select_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_select_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_gain_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_gain_panel, 200);
    lv_obj_set_height(ObjsCt->ui_gain_panel, 62);
    lv_obj_set_x(ObjsCt->ui_gain_panel, 15);
    lv_obj_set_y(ObjsCt->ui_gain_panel, 66);
    lv_obj_clear_flag(ObjsCt->ui_gain_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_gain_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_gain_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_gain_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_gain_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_gain_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_gain_name = lv_label_create(ObjsCt->ui_gain_panel);
    lv_obj_set_width(ObjsCt->ui_gain_name, 200);
    lv_obj_set_height(ObjsCt->ui_gain_name, 31);
    lv_obj_set_align(ObjsCt->ui_gain_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_gain_name, "GAIN");
    lv_obj_set_style_text_color(ObjsCt->ui_gain_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_gain_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_gain_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_gain_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_gain_args = lv_label_create(ObjsCt->ui_gain_panel);
    lv_obj_set_width(ObjsCt->ui_gain_args, 200);
    lv_obj_set_height(ObjsCt->ui_gain_args, 31);
    lv_obj_set_align(ObjsCt->ui_gain_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_gain_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_gain_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_gain_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_gain_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_gain_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_phantom_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_phantom_panel, 200);
    lv_obj_set_height(ObjsCt->ui_phantom_panel, 62);
    lv_obj_set_x(ObjsCt->ui_phantom_panel, 15);
    lv_obj_set_y(ObjsCt->ui_phantom_panel, 130);
    lv_obj_clear_flag(ObjsCt->ui_phantom_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_phantom_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_phantom_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_phantom_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_phantom_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_phantom_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_phantom_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_phantom_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_phantom_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_phantom_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_phantom_name = lv_label_create(ObjsCt->ui_phantom_panel);
    lv_obj_set_width(ObjsCt->ui_phantom_name, 200);
    lv_obj_set_height(ObjsCt->ui_phantom_name, 31);
    lv_obj_set_align(ObjsCt->ui_phantom_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_phantom_name, "PHANTOM");
    lv_obj_set_style_text_color(ObjsCt->ui_phantom_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_phantom_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_phantom_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_phantom_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_phantom_args = lv_label_create(ObjsCt->ui_phantom_panel);
    lv_obj_set_width(ObjsCt->ui_phantom_args, 200);
    lv_obj_set_height(ObjsCt->ui_phantom_args, 31);
    lv_obj_set_align(ObjsCt->ui_phantom_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_phantom_args, "48V");
    lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_phantom_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_phantom_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_phantom_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fx_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_fx_panel, 200);
    lv_obj_set_height(ObjsCt->ui_fx_panel, 62);
    lv_obj_set_x(ObjsCt->ui_fx_panel, 15);
    lv_obj_set_y(ObjsCt->ui_fx_panel, 194);
    lv_obj_clear_flag(ObjsCt->ui_fx_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_fx_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_fx_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_fx_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_fx_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_fx_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fx_name = lv_label_create(ObjsCt->ui_fx_panel);
    lv_obj_set_width(ObjsCt->ui_fx_name, 200);
    lv_obj_set_height(ObjsCt->ui_fx_name, 31);
    lv_obj_set_align(ObjsCt->ui_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_fx_name, "FX VOL");
    lv_obj_set_style_text_color(ObjsCt->ui_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fx_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fx_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fx_args = lv_label_create(ObjsCt->ui_fx_panel);
    lv_obj_set_width(ObjsCt->ui_fx_args, 200);
    lv_obj_set_height(ObjsCt->ui_fx_args, 31);
    lv_obj_set_align(ObjsCt->ui_fx_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_fx_args, "+10");
    lv_obj_set_style_text_color(ObjsCt->ui_fx_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fx_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fx_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fx_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hi_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_hi_panel, 200);
    lv_obj_set_height(ObjsCt->ui_hi_panel, 62);
    lv_obj_set_x(ObjsCt->ui_hi_panel, 262);
    lv_obj_set_y(ObjsCt->ui_hi_panel, 2);
    lv_obj_clear_flag(ObjsCt->ui_hi_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_hi_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_hi_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_hi_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_hi_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_hi_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hi_name = lv_label_create(ObjsCt->ui_hi_panel);
    lv_obj_set_width(ObjsCt->ui_hi_name, 200);
    lv_obj_set_height(ObjsCt->ui_hi_name, 31);
    lv_obj_set_align(ObjsCt->ui_hi_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_hi_name, "HI 10KHz");
    lv_obj_set_style_text_color(ObjsCt->ui_hi_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hi_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hi_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hi_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hi_args = lv_label_create(ObjsCt->ui_hi_panel);
    lv_obj_set_width(ObjsCt->ui_hi_args, 200);
    lv_obj_set_height(ObjsCt->ui_hi_args, 31);
    lv_obj_set_align(ObjsCt->ui_hi_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_hi_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_hi_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hi_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hi_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hi_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_mid_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_mid_panel, 200);
    lv_obj_set_height(ObjsCt->ui_mid_panel, 62);
    lv_obj_set_x(ObjsCt->ui_mid_panel, 262);
    lv_obj_set_y(ObjsCt->ui_mid_panel, 66);
    lv_obj_clear_flag(ObjsCt->ui_mid_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_mid_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_mid_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_mid_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_mid_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_mid_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_mid_name = lv_label_create(ObjsCt->ui_mid_panel);
    lv_obj_set_width(ObjsCt->ui_mid_name, 200);
    lv_obj_set_height(ObjsCt->ui_mid_name, 31);
    lv_obj_set_align(ObjsCt->ui_mid_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_mid_name, "MID 2.5KHz");
    lv_obj_set_style_text_color(ObjsCt->ui_mid_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_mid_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_mid_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_mid_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_mid_args = lv_label_create(ObjsCt->ui_mid_panel);
    lv_obj_set_width(ObjsCt->ui_mid_args, 200);
    lv_obj_set_height(ObjsCt->ui_mid_args, 31);
    lv_obj_set_align(ObjsCt->ui_mid_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_mid_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_mid_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_mid_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_mid_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_mid_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_low_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_low_panel, 200);
    lv_obj_set_height(ObjsCt->ui_low_panel, 62);
    lv_obj_set_x(ObjsCt->ui_low_panel, 262);
    lv_obj_set_y(ObjsCt->ui_low_panel, 130);
    lv_obj_clear_flag(ObjsCt->ui_low_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_low_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_low_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_low_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_low_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_low_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_low_name = lv_label_create(ObjsCt->ui_low_panel);
    lv_obj_set_width(ObjsCt->ui_low_name, 200);
    lv_obj_set_height(ObjsCt->ui_low_name, 31);
    lv_obj_set_align(ObjsCt->ui_low_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_low_name, "LOW 80Hz");
    lv_obj_set_style_text_color(ObjsCt->ui_low_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_low_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_low_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_low_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_low_args = lv_label_create(ObjsCt->ui_low_panel);
    lv_obj_set_width(ObjsCt->ui_low_args, 200);
    lv_obj_set_height(ObjsCt->ui_low_args, 31);
    lv_obj_set_align(ObjsCt->ui_low_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_low_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_low_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_low_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_low_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_low_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hpf_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_hpf_panel, 200);
    lv_obj_set_height(ObjsCt->ui_hpf_panel, 62);
    lv_obj_set_x(ObjsCt->ui_hpf_panel, 262);
    lv_obj_set_y(ObjsCt->ui_hpf_panel, 194);
    lv_obj_clear_flag(ObjsCt->ui_hpf_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_hpf_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_hpf_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_hpf_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_hpf_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_hpf_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_hpf_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_hpf_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_hpf_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_hpf_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hpf_name = lv_label_create(ObjsCt->ui_hpf_panel);
    lv_obj_set_width(ObjsCt->ui_hpf_name, 200);
    lv_obj_set_height(ObjsCt->ui_hpf_name, 31);
    lv_obj_set_align(ObjsCt->ui_hpf_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_hpf_name, "MIC HPF");
    lv_obj_set_style_text_color(ObjsCt->ui_hpf_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hpf_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hpf_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hpf_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hpf_args = lv_label_create(ObjsCt->ui_hpf_panel);
    lv_obj_set_width(ObjsCt->ui_hpf_args, 200);
    lv_obj_set_height(ObjsCt->ui_hpf_args, 31);
    lv_obj_set_align(ObjsCt->ui_hpf_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_hpf_args, "80Hz");
    lv_obj_set_style_text_color(ObjsCt->ui_hpf_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hpf_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hpf_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hpf_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fbe_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_fbe_panel, 200);
    lv_obj_set_height(ObjsCt->ui_fbe_panel, 62);
    lv_obj_set_x(ObjsCt->ui_fbe_panel, 15);
    lv_obj_set_y(ObjsCt->ui_fbe_panel, 258);
    lv_obj_clear_flag(ObjsCt->ui_fbe_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_fbe_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_fbe_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_fbe_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_fbe_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_fbe_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_fbe_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_fbe_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_fbe_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_fbe_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fbe_name = lv_label_create(ObjsCt->ui_fbe_panel);
    lv_obj_set_width(ObjsCt->ui_fbe_name, 200);
    lv_obj_set_height(ObjsCt->ui_fbe_name, 31);
    lv_obj_set_align(ObjsCt->ui_fbe_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_fbe_name, "MIC FBE");
    lv_obj_set_style_text_color(ObjsCt->ui_fbe_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fbe_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fbe_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fbe_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fbe_args = lv_label_create(ObjsCt->ui_fbe_panel);
    lv_obj_set_width(ObjsCt->ui_fbe_args, 200);
    lv_obj_set_height(ObjsCt->ui_fbe_args, 31);
    lv_obj_set_align(ObjsCt->ui_fbe_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_fbe_args, "ON");
    lv_obj_set_style_text_color(ObjsCt->ui_fbe_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fbe_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fbe_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fbe_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_pan_panel = lv_obj_create(ObjsCt->Mic1_obj);
    lv_obj_set_width(ObjsCt->ui_pan_panel, 200);
    lv_obj_set_height(ObjsCt->ui_pan_panel, 62);
    lv_obj_set_x(ObjsCt->ui_pan_panel, 262);
    lv_obj_set_y(ObjsCt->ui_pan_panel, 258);
    lv_obj_clear_flag(ObjsCt->ui_pan_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ObjsCt->ui_pan_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_pan_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_pan_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_pan_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_pan_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_pan_name = lv_label_create(ObjsCt->ui_pan_panel);
    lv_obj_set_width(ObjsCt->ui_pan_name, 200);
    lv_obj_set_height(ObjsCt->ui_pan_name, 31);
    lv_obj_set_align(ObjsCt->ui_pan_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_pan_name, "PAN");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_pan_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_pan_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);


    ObjsCt->ui_pan_args = lv_label_create(ObjsCt->ui_pan_panel);
    lv_obj_add_flag(ObjsCt->ui_pan_args, LV_OBJ_FLAG_HIDDEN);  

    ObjsCt->ui_pan_label_L = lv_label_create(ObjsCt->ui_pan_panel);
    lv_label_set_text(ObjsCt->ui_pan_label_L, "L");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_label_L, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ObjsCt->ui_pan_label_L, 55, 31);  

    ObjsCt->ui_pan_label_R = lv_label_create(ObjsCt->ui_pan_panel);
    lv_label_set_text(ObjsCt->ui_pan_label_R, "R");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_label_R, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ObjsCt->ui_pan_label_R, 130, 31);
    

    ui_page_mic1_gain_arg_refresh(ArgsCt.gain_args);
    ui_page_mic1_phantom_arg_refresh(ArgsCt.phantom_args);
    ui_page_mic1_fx_arg_refresh(ArgsCt.fx_args);
    ui_page_mic1_hi_arg_refresh(ArgsCt.hi_args);
    ui_page_mic1_mid_arg_refresh(ArgsCt.mid_args);
    ui_page_mic1_low_arg_refresh(ArgsCt.low_args);
    ui_page_mic1_hpf_arg_refresh(ArgsCt.hpf_args);
    ui_page_mic1_fbe_arg_refresh(ArgsCt.fbe_args);
    ui_page_mic1_pan_arg_refresh(ArgsCt.pan_args);


    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    switch(ArgsCt.focus_target)
    {
        case 0: lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 1: lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 2: lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 3: lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 4: lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 5: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 6: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 7: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 8: lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 9: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        default: break;
    }


    if(ArgsCt.edit_mode)
    {
        lv_color_t text_color = lv_color_hex(0xFFA500);
        switch(ArgsCt.focus_target)
        {
            case 0: lv_obj_set_style_text_color(ObjsCt->ui_select_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 1: lv_obj_set_style_text_color(ObjsCt->ui_gain_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 2: lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 3: lv_obj_set_style_text_color(ObjsCt->ui_fx_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 4: lv_obj_set_style_text_color(ObjsCt->ui_fbe_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 5: lv_obj_set_style_text_color(ObjsCt->ui_hi_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 6: lv_obj_set_style_text_color(ObjsCt->ui_mid_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 7: lv_obj_set_style_text_color(ObjsCt->ui_low_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 8: lv_obj_set_style_text_color(ObjsCt->ui_hpf_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 9: lv_obj_set_style_text_color(ObjsCt->ui_pan_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            default: break;
        }
    }
}


void ui_page_Mic1_start(void)
{
    if(ObjsCt == NULL)
        return;

    ArgsCt.focus_target = 0;
    ArgsCt.edit_mode = 0;

    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ObjsCt->ui_select_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_gain_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_fx_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_hi_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_mid_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_low_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_hpf_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_fbe_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_pan_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_page_Mic1_exit(uint8_t del)
{
    if(del)
    {

    }
    else
    {

    }
    SendBuf[9] = 0x00;//退出当前页面，让从机关闭LED灯
    MasterSendExample(0x22);
}

void ui_page_Mic1_clean(void)
{
    lv_mem_free(ObjsCt);
    ObjsCt = NULL;
}

void ui_page_Mic1_request(uint32_t delay)
{
    switch(ui_pmanagerCt.id_tar)
    {

        case UI_PAGE_SEL_1:
            break;

        default:
            ui_pmanager_switch(UI_PAGE_SEL_1, delay, true);
            break;
    }
    SendBuf[9] = 0x01;//进入当前页面，让从机开启LED灯
    MasterSendExample(0x22);
}


static const char *gain_args_table[] = {
    "0db", "+1db", "+2db", "+3db", "+4db", "+5db", "+6db", "+7db",
    "+8db", "+9db", "+10db", "+11db", "+12db", "+13db", "+14db", "+15db",
    "+16db", "+17db", "+18db", "+19db", "+20db", "+21db", "+22db", "+23db",
    "+24db", "+25db", "+26db", "+27db", "+28db", "+29db", "+30db"
};


void ui_page_mic1_gain_arg_refresh(uint8_t argVal)
{
    ArgsCt.gain_args = argVal;
    lv_label_set_text(ObjsCt->ui_gain_args, gain_args_table[argVal]);
}


static const char *phantom_args_table[] = {
    "OFF", "ON"
};


void ui_page_mic1_phantom_arg_refresh(uint8_t argVal)
{
    ArgsCt.phantom_args = argVal;
    lv_label_set_text(ObjsCt->ui_phantom_args, phantom_args_table[argVal]);
}


static const char *fx_args_table[] = {
    "0db", "+1db", "+2db", "+3db", "+4db", "+5db",
    "+6db", "+7db", "+8db", "+9db", "+10db"
};


static const char *eq_args_table[] = {
    "-15db", "-14db", "-13db", "-12db", "-11db", "-10db", "-9db", "-8db",
    "-7db", "-6db", "-5db", "-4db", "-3db", "-2db", "-1db", "0db",
    "+1db", "+2db", "+3db", "+4db", "+5db", "+6db", "+7db", "+8db",
    "+9db", "+10db", "+11db", "+12db", "+13db", "+14db", "+15db"
};

static const char *hpf_args_table[] = {
    "80Hz", "120Hz", "200Hz"
};

static const char *fbe_args_table[] = {
    "OFF", "ON"
};

void ui_page_mic1_hpf_arg_refresh(uint8_t argVal)
{
    ArgsCt.hpf_args = argVal;
    lv_label_set_text(ObjsCt->ui_hpf_args, hpf_args_table[argVal]);
}

void ui_page_mic1_fbe_arg_refresh(uint8_t argVal)
{
    ArgsCt.fbe_args = argVal;
    lv_label_set_text(ObjsCt->ui_fbe_args, fbe_args_table[argVal]);
}


void ui_page_mic1_pan_arg_refresh(uint8_t argVal)
{
    ArgsCt.pan_args = argVal;
    
    // 所有label默认白色
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 根据选中值设置对应label为橙色
    switch(argVal)
    {
        case 0: // 不选（都是橙色）
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 1: // 选中L
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 2: // 选中R
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
    }
}

void ui_page_mic1_fx_arg_refresh(uint8_t argVal)
{
    ArgsCt.fx_args = argVal;
    lv_label_set_text(ObjsCt->ui_fx_args, fx_args_table[argVal]);
}

void ui_page_mic1_hi_arg_refresh(uint8_t argVal)
{
    ArgsCt.hi_args = argVal;
    lv_label_set_text(ObjsCt->ui_hi_args, eq_args_table[argVal]);
}

void ui_page_mic1_mid_arg_refresh(uint8_t argVal)
{
    ArgsCt.mid_args = argVal;
    lv_label_set_text(ObjsCt->ui_mid_args, eq_args_table[argVal]);
}

void ui_page_mic1_low_arg_refresh(uint8_t argVal)
{
    ArgsCt.low_args = argVal;
    lv_label_set_text(ObjsCt->ui_low_args, eq_args_table[argVal]);
}


void ui_page_Mic1_encoder_up(void)
{
    if(ObjsCt == NULL) return;
    
    if(ArgsCt.edit_mode == 0)
    {
        switch(ArgsCt.focus_target)
        {
            case 0:
                lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 1:
                lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 2:
                lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 3:
                lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 4: lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 5: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 6: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 7: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 8: lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 9: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
        }
        
        if(ArgsCt.focus_target < 9)
        {
            ArgsCt.focus_target++;
        }
        else
        {
            ArgsCt.focus_target = 0;
        }
        
        switch(ArgsCt.focus_target)
        {
            case 0:
                lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 1:
                lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 2:
                lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 3:
                lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 4: 
                lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 5: 
                lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 6: 
                lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 7: 
                lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 8: 
                lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 9: 
                lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
        }
        
    }
    else 
    {
        switch(ArgsCt.focus_target)
        {
            case 1: // gain panel
                if(ArgsCt.gain_args < sizeof(gain_args_table)/sizeof(gain_args_table[0]) - 1)
                {
                    ArgsCt.gain_args++;
                    ui_page_mic1_gain_arg_refresh(ArgsCt.gain_args);
                }
                break;
            case 2: // phantom panel - ON/OFF switch
                if(ArgsCt.phantom_args < 1)  // 0=OFF, 1=ON
                {
                    ArgsCt.phantom_args++;
                    ui_page_mic1_phantom_arg_refresh(ArgsCt.phantom_args);
                }
                break;
            case 3: // fx panel
                if(ArgsCt.fx_args < sizeof(fx_args_table)/sizeof(fx_args_table[0]) - 1)
                {
                    ArgsCt.fx_args++;
                    ui_page_mic1_fx_arg_refresh(ArgsCt.fx_args);
                }
                break;
            case 4: // fbe panel (MIC FBE)
                if(ArgsCt.fbe_args < sizeof(fbe_args_table)/sizeof(fbe_args_table[0]) - 1)
                {
                    ArgsCt.fbe_args++;
                    ui_page_mic1_fbe_arg_refresh(ArgsCt.fbe_args);
                }
                break;
            case 5: // hi panel
                if(ArgsCt.hi_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1)
                {
                    ArgsCt.hi_args++;
                    ui_page_mic1_hi_arg_refresh(ArgsCt.hi_args);
                }
                break;
            case 6: // mid panel
                if(ArgsCt.mid_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1)
                {
                    ArgsCt.mid_args++;
                    ui_page_mic1_mid_arg_refresh(ArgsCt.mid_args);
                }
                break;
            case 7: // low panel
                if(ArgsCt.low_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1)
                {
                    ArgsCt.low_args++;
                    ui_page_mic1_low_arg_refresh(ArgsCt.low_args);
                }
                break;
            case 8: // pan panel (MIC HPF: 80Hz/120Hz/200Hz)
                if(ArgsCt.hpf_args < sizeof(hpf_args_table)/sizeof(hpf_args_table[0]) - 1)
                {
                    ArgsCt.hpf_args++;
                    ui_page_mic1_hpf_arg_refresh(ArgsCt.hpf_args);
                }
                break;
            case 9: // pan2 panel (PAN: L/R)
                if(ArgsCt.pan_args < 2)  // 0=不选, 1=L, 2=R
                {
                    ArgsCt.pan_args++;
                    ui_page_mic1_pan_arg_refresh(ArgsCt.pan_args);
                }
                break;
        }
    }
}

void ui_page_Mic1_encoder_down(void)
{
    if(ObjsCt == NULL) return; 
    
    if(ArgsCt.edit_mode == 0)
    {
        switch(ArgsCt.focus_target)
        {
            case 0:
                lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 1:
                lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 2:
                lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 3:
                lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 4: lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 5: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 6: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 7: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 8: lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 9: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
        }
        
        if(ArgsCt.focus_target > 0)
        {
            ArgsCt.focus_target--;
        }
        else
        {
            ArgsCt.focus_target = 9;
        }
        
        switch(ArgsCt.focus_target)
        {
            case 0:
                lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 1:
                lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 2:
                lv_obj_set_style_border_color(ObjsCt->ui_phantom_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 3:
                lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 4: lv_obj_set_style_border_color(ObjsCt->ui_fbe_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 5: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 6: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 7: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 8: lv_obj_set_style_border_color(ObjsCt->ui_hpf_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
            case 9: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
                break;
        }
        
    }
    else
    {
        switch(ArgsCt.focus_target)
        {
            case 1: // gain panel
                if(ArgsCt.gain_args > 0)
                {
                    ArgsCt.gain_args--;
                    ui_page_mic1_gain_arg_refresh(ArgsCt.gain_args);
                }
                break;
            case 2: // phantom panel - ON/OFF switch
                if(ArgsCt.phantom_args > 0)  // 0=OFF, 1=ON
                {
                    ArgsCt.phantom_args--;
                    ui_page_mic1_phantom_arg_refresh(ArgsCt.phantom_args);
                }
                break;
            case 3: // fx panel
                if(ArgsCt.fx_args > 0)
                {
                    ArgsCt.fx_args--;
                    ui_page_mic1_fx_arg_refresh(ArgsCt.fx_args);
                }
                break;
            case 4: // fbe panel (MIC FBE)
                if(ArgsCt.fbe_args > 0)
                {
                    ArgsCt.fbe_args--;
                    ui_page_mic1_fbe_arg_refresh(ArgsCt.fbe_args);
                }
                break;
            case 5: // hi panel
                if(ArgsCt.hi_args > 0)
                {
                    ArgsCt.hi_args--;
                    ui_page_mic1_hi_arg_refresh(ArgsCt.hi_args);
                }
                break;
            case 6: // mid panel
                if(ArgsCt.mid_args > 0)
                {
                    ArgsCt.mid_args--;
                    ui_page_mic1_mid_arg_refresh(ArgsCt.mid_args);
                }
                break;
            case 7: // low panel
                if(ArgsCt.low_args > 0)
                {
                    ArgsCt.low_args--;
                    ui_page_mic1_low_arg_refresh(ArgsCt.low_args);
                }
                break;
            case 8: // pan panel
                if(ArgsCt.hpf_args > 0)
                {
                    ArgsCt.hpf_args--;
                    ui_page_mic1_hpf_arg_refresh(ArgsCt.hpf_args);
                }
                break;
            case 9: // pan2 panel (PAN: L/C/R)
                if(ArgsCt.pan_args > 0)
                {
                    ArgsCt.pan_args--;
                    ui_page_mic1_pan_arg_refresh(ArgsCt.pan_args);
                }
                break;
        }
    }
}

void ui_page_Mic1_encoder_ok(void)
{
    if(ObjsCt == NULL) return;
    
    if(ArgsCt.focus_target == 2)
    {
        if(ArgsCt.edit_mode == 0)
        {
            ArgsCt.edit_mode = 1;
            lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        else
        {
            ArgsCt.edit_mode = 0;
            lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        return;
    }
    
    ArgsCt.edit_mode = !ArgsCt.edit_mode;
    
    lv_color_t text_color = ArgsCt.edit_mode ? lv_color_hex(0xFFA500) : lv_color_hex(0xFFFFFF);
    
    switch(ArgsCt.focus_target)
    {
        case 0:
            lv_obj_set_style_text_color(ObjsCt->ui_select_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 1:
            lv_obj_set_style_text_color(ObjsCt->ui_gain_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 2:
            lv_obj_set_style_text_color(ObjsCt->ui_phantom_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 3:
            lv_obj_set_style_text_color(ObjsCt->ui_fx_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 4:
            lv_obj_set_style_text_color(ObjsCt->ui_fbe_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 5:
            lv_obj_set_style_text_color(ObjsCt->ui_hi_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 6:
            lv_obj_set_style_text_color(ObjsCt->ui_mid_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 7:
            lv_obj_set_style_text_color(ObjsCt->ui_low_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 8:
            lv_obj_set_style_text_color(ObjsCt->ui_hpf_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 9:
            lv_obj_set_style_text_color(ObjsCt->ui_pan_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
    }
}
