/*
 * @Author: wujunpeng
 * @Date: 2025-11-27 12:23:03
 * @LastEditors: Do not edit
 * @LastEditTime: 2026-02-03 18:02:40
 * @FilePath: \lvgl_digtial_v01\MVsB1_BT_Karaoke_SDK_v0.3.3\BT_Audio_APP\bt_audio_app_src\lvgl_apps\ui_page_mic2\ui_page_mic2.h
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PAGE_Mic2_H
#define UI_PAGE_Mic2_H

/*################################### include ###################################*/
#include "type.h"
#include "lvgl.h"

/*################################### define/enum ###################################*/

/*################################### typedef ###################################*/
typedef struct _Mic2ObjsContext_{
    lv_obj_t *Mic2_obj;
    lv_obj_t *ui_select_panel;
    lv_obj_t *ui_select_name;
    lv_obj_t *ui_select_args; 
    lv_obj_t *ui_gain_panel; 
    lv_obj_t *ui_gain_name; 
    lv_obj_t *ui_gain_args; 
    lv_obj_t *ui_phantom_panel; 
    lv_obj_t *ui_phantom_name; 
    lv_obj_t *ui_phantom_args; 
    lv_obj_t *ui_fx_panel; 
    lv_obj_t *ui_fx_name; 
    lv_obj_t *ui_fx_args; 
    lv_obj_t *ui_hi_panel; 
    lv_obj_t *ui_hi_name;
    lv_obj_t *ui_hi_args;
    lv_obj_t *ui_mid_panel;
    lv_obj_t *ui_mid_name;
    lv_obj_t *ui_mid_args;
    lv_obj_t *ui_low_panel;
    lv_obj_t *ui_low_name;
    lv_obj_t *ui_low_args;
    lv_obj_t *ui_hpf_panel;
    lv_obj_t *ui_hpf_name;
    lv_obj_t *ui_hpf_args;
    lv_obj_t *ui_fbe_panel;
    lv_obj_t *ui_fbe_name;
    lv_obj_t *ui_fbe_args;
    lv_obj_t *ui_pan_panel;
    lv_obj_t *ui_pan_name;
    lv_obj_t *ui_pan_args;
    lv_obj_t *ui_pan_label_L;  // PAN��L��ĸ
    lv_obj_t *ui_pan_label_R;  // PAN��R��ĸ
} Mic2ObjsContext;

typedef struct _Mic2ArgsContext_
{
    uint8_t focus_target;
    uint8_t edit_mode;      // �༭ģʽ, 0=���ѡ��ģʽ, 1=�����༭ģʽ
    uint8_t gain_args;
    uint8_t phantom_args;
    uint8_t fx_args;
    uint8_t hi_args;
    uint8_t mid_args;
    uint8_t low_args;
    uint8_t hpf_args;       // MIC HPF����: 0=80Hz, 1=120Hz, 2=200Hz
    uint8_t fbe_args;       // MIC FBE����: 0=OFF, 1=ON
    uint8_t pan_args;       // PAN����: 0=L(��ɫ), 1=C(��ɫ), 2=R(��ɫ)����ʾ"L C R"��ѡ�����ɫ

} Mic2ArgsContext;

/*################################### ȫ�ֱ��� ###################################*/

/*################################### ȫ�ֺ��� ###################################*/
void ui_page_Mic2_init(lv_obj_t *screen);
void ui_page_Mic2_start(void);
void ui_page_Mic2_exit(uint8_t del);
void ui_page_Mic2_clean(void);
void ui_page_Mic2_request(uint32_t delay);
#endif
