; MVA config file     2022.08.30  

[fileset]
output_path = ..\..\..\BT_Audio_APP\Debug\output\main_merge.mva

[chipinfo] ;01
PID= chipinfo
full_path=chipinfo.bin
src_offset = 0x0
src_len = 0x0
des_address = 0x0
chip_type = 0xB2
flash_capacity_set = 2048  
max_len = 0x0


[code]  ;02 
PID= code
full_path=..\..\..\BT_Audio_APP\Debug\output\BT_Audio_APP.bin
src_offset = 0x0
src_len = 0x0
crc_len = boot_len
des_address = 0x0
max_len = 0x200000


[data]  ;04 
PID= data
full_path=..\remind_script\all.bin
src_offset = 0x0
src_len = 0x0
des_address = 0x160000
max_len = 0x50000




