// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include "ui_page_Aux1.h"
#include "string.h"
#include "stdio.h"
#include "ui_pmanager.h"
#include "my_i2c_driver.h"
/*################################### 宏定义 ###################################*/

/*################################### 变量(静态声明) ###################################*/

/*################################### 变量(全局声明) ###################################*/

/*################################### 变量(静态定义) ###################################*/
static Aux1ObjsContext *ObjsCt;
static Aux1ArgsContext ArgsCt;
static uint8_t args_initialized;

/*################################### 变量(全局定义) ###################################*/

/*################################### 函数(静态声明) ###################################*/

/*################################### 函数(全局声明) ###################################*/

/*################################### 函数(静态定义) ###################################*/

void ui_page_Aux1_init(lv_obj_t *screen)
{
    //内存分配
    {
        ObjsCt = (Aux1ObjsContext *)lv_mem_alloc(sizeof(Aux1ObjsContext));
        memset(ObjsCt, 0, sizeof(Aux1ObjsContext));
        if(!args_initialized)
        {
            memset(&ArgsCt, 0, sizeof(Aux1ArgsContext));
            ArgsCt.focus_target = 0;
            ArgsCt.edit_mode = 0;
            ArgsCt.gain_args = 0;       // 默认 0db (索引0，共31个值: 0db到30db)
            ArgsCt.fx_args = 0;         // 默认 0db (索引0，共11个值: 0db到10db)
            ArgsCt.hi_args = 15;        // 默认 0db (索引15，共31个值: -15db到15db)
            ArgsCt.mid_args = 15;       // 默认 0db (索引15)
            ArgsCt.low_args = 15;       // 默认 0db (索引15)
            ArgsCt.hpf_args = 1;        // 默认 120Hz (索引1：MIC HPF 120Hz)
            ArgsCt.pan_args = 0;        // 默认不选（索引0：0=不选, 1=L, 2=R）
            args_initialized = 1;
        }
    }

    ObjsCt->Aux1_obj = lv_img_create(screen);
    lv_obj_set_size(ObjsCt->Aux1_obj, 480, 320);
    lv_obj_set_style_bg_color(ObjsCt->Aux1_obj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->Aux1_obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ObjsCt->Aux1_obj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Panel 1: SELECTS (15, 2)
    ObjsCt->ui_select_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_select_panel, 200);
    lv_obj_set_height(ObjsCt->ui_select_panel, 62);
    lv_obj_set_x(ObjsCt->ui_select_panel, 15);
    lv_obj_set_y(ObjsCt->ui_select_panel, 2);
    lv_obj_clear_flag(ObjsCt->ui_select_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_select_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_select_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_select_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_select_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_select_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_select_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_select_name = lv_label_create(ObjsCt->ui_select_panel);
    lv_obj_set_width(ObjsCt->ui_select_name, 200);
    lv_obj_set_height(ObjsCt->ui_select_name, 31);
    lv_obj_set_align(ObjsCt->ui_select_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_select_name, "SELECTS");
    lv_obj_set_style_text_color(ObjsCt->ui_select_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_select_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_select_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_select_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_select_args = lv_label_create(ObjsCt->ui_select_panel);
    lv_obj_set_width(ObjsCt->ui_select_args, 200);
    lv_obj_set_height(ObjsCt->ui_select_args, 31);
    lv_obj_set_align(ObjsCt->ui_select_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_select_args, "3/4");
    lv_obj_set_style_text_color(ObjsCt->ui_select_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_select_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_select_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_select_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 2: GAIN (15, 66)
    ObjsCt->ui_gain_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_gain_panel, 200);
    lv_obj_set_height(ObjsCt->ui_gain_panel, 62);
    lv_obj_set_x(ObjsCt->ui_gain_panel, 15);
    lv_obj_set_y(ObjsCt->ui_gain_panel, 66);
    lv_obj_clear_flag(ObjsCt->ui_gain_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_gain_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_gain_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_gain_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_gain_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_gain_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_gain_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_gain_name = lv_label_create(ObjsCt->ui_gain_panel);
    lv_obj_set_width(ObjsCt->ui_gain_name, 200);
    lv_obj_set_height(ObjsCt->ui_gain_name, 31);
    lv_obj_set_align(ObjsCt->ui_gain_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_gain_name, "GAIN");
    lv_obj_set_style_text_color(ObjsCt->ui_gain_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_gain_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_gain_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_gain_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_gain_args = lv_label_create(ObjsCt->ui_gain_panel);
    lv_obj_set_width(ObjsCt->ui_gain_args, 200);
    lv_obj_set_height(ObjsCt->ui_gain_args, 31);
    lv_obj_set_align(ObjsCt->ui_gain_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_gain_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_gain_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_gain_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_gain_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_gain_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 3: FX VOL (15, 130)
    ObjsCt->ui_fx_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_fx_panel, 200);
    lv_obj_set_height(ObjsCt->ui_fx_panel, 62);
    lv_obj_set_x(ObjsCt->ui_fx_panel, 15);
    lv_obj_set_y(ObjsCt->ui_fx_panel, 130);
    lv_obj_clear_flag(ObjsCt->ui_fx_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_fx_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_fx_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_fx_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_fx_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_fx_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_fx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fx_name = lv_label_create(ObjsCt->ui_fx_panel);
    lv_obj_set_width(ObjsCt->ui_fx_name, 200);
    lv_obj_set_height(ObjsCt->ui_fx_name, 31);
    lv_obj_set_align(ObjsCt->ui_fx_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_fx_name, "FX VOL");
    lv_obj_set_style_text_color(ObjsCt->ui_fx_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fx_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fx_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fx_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_fx_args = lv_label_create(ObjsCt->ui_fx_panel);
    lv_obj_set_width(ObjsCt->ui_fx_args, 200);
    lv_obj_set_height(ObjsCt->ui_fx_args, 31);
    lv_obj_set_align(ObjsCt->ui_fx_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_fx_args, "+10");
    lv_obj_set_style_text_color(ObjsCt->ui_fx_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_fx_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_fx_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_fx_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 4: HI 10KHz (262, 2)
    ObjsCt->ui_hi_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_hi_panel, 200);
    lv_obj_set_height(ObjsCt->ui_hi_panel, 62);
    lv_obj_set_x(ObjsCt->ui_hi_panel, 262);
    lv_obj_set_y(ObjsCt->ui_hi_panel, 2);
    lv_obj_clear_flag(ObjsCt->ui_hi_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_hi_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_hi_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_hi_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_hi_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_hi_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_hi_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hi_name = lv_label_create(ObjsCt->ui_hi_panel);
    lv_obj_set_width(ObjsCt->ui_hi_name, 200);
    lv_obj_set_height(ObjsCt->ui_hi_name, 31);
    lv_obj_set_align(ObjsCt->ui_hi_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_hi_name, "HI 10KHz");
    lv_obj_set_style_text_color(ObjsCt->ui_hi_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hi_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hi_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hi_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_hi_args = lv_label_create(ObjsCt->ui_hi_panel);
    lv_obj_set_width(ObjsCt->ui_hi_args, 200);
    lv_obj_set_height(ObjsCt->ui_hi_args, 31);
    lv_obj_set_align(ObjsCt->ui_hi_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_hi_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_hi_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_hi_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_hi_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_hi_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 5: MID 2.5KHz (262, 66)
    ObjsCt->ui_mid_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_mid_panel, 200);
    lv_obj_set_height(ObjsCt->ui_mid_panel, 62);
    lv_obj_set_x(ObjsCt->ui_mid_panel, 262);
    lv_obj_set_y(ObjsCt->ui_mid_panel, 66);
    lv_obj_clear_flag(ObjsCt->ui_mid_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_mid_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_mid_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_mid_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_mid_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_mid_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_mid_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_mid_name = lv_label_create(ObjsCt->ui_mid_panel);
    lv_obj_set_width(ObjsCt->ui_mid_name, 200);
    lv_obj_set_height(ObjsCt->ui_mid_name, 31);
    lv_obj_set_align(ObjsCt->ui_mid_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_mid_name, "MID 2.5KHz");
    lv_obj_set_style_text_color(ObjsCt->ui_mid_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_mid_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_mid_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_mid_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_mid_args = lv_label_create(ObjsCt->ui_mid_panel);
    lv_obj_set_width(ObjsCt->ui_mid_args, 200);
    lv_obj_set_height(ObjsCt->ui_mid_args, 31);
    lv_obj_set_align(ObjsCt->ui_mid_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_mid_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_mid_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_mid_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_mid_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_mid_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 6: LOW 80Hz (262, 130)
    ObjsCt->ui_low_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_low_panel, 200);
    lv_obj_set_height(ObjsCt->ui_low_panel, 62);
    lv_obj_set_x(ObjsCt->ui_low_panel, 262);
    lv_obj_set_y(ObjsCt->ui_low_panel, 130);
    lv_obj_clear_flag(ObjsCt->ui_low_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_low_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_low_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_low_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_low_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_low_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_low_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_low_name = lv_label_create(ObjsCt->ui_low_panel);
    lv_obj_set_width(ObjsCt->ui_low_name, 200);
    lv_obj_set_height(ObjsCt->ui_low_name, 31);
    lv_obj_set_align(ObjsCt->ui_low_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_low_name, "LOW 80Hz");
    lv_obj_set_style_text_color(ObjsCt->ui_low_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_low_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_low_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_low_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_low_args = lv_label_create(ObjsCt->ui_low_panel);
    lv_obj_set_width(ObjsCt->ui_low_args, 200);
    lv_obj_set_height(ObjsCt->ui_low_args, 31);
    lv_obj_set_align(ObjsCt->ui_low_args, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ObjsCt->ui_low_args, "0db");
    lv_obj_set_style_text_color(ObjsCt->ui_low_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_low_args, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_low_args, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_low_args, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Panel 7: PAN (15, 194)
    ObjsCt->ui_pan_panel = lv_obj_create(ObjsCt->Aux1_obj);
    lv_obj_set_width(ObjsCt->ui_pan_panel, 200);
    lv_obj_set_height(ObjsCt->ui_pan_panel, 62);
    lv_obj_set_x(ObjsCt->ui_pan_panel, 15);
    lv_obj_set_y(ObjsCt->ui_pan_panel, 194);
    lv_obj_clear_flag(ObjsCt->ui_pan_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ObjsCt->ui_pan_panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ObjsCt->ui_pan_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ObjsCt->ui_pan_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ObjsCt->ui_pan_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ObjsCt->ui_pan_panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ObjsCt->ui_pan_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ObjsCt->ui_pan_name = lv_label_create(ObjsCt->ui_pan_panel);
    lv_obj_set_width(ObjsCt->ui_pan_name, 200);
    lv_obj_set_height(ObjsCt->ui_pan_name, 31);
    lv_obj_set_align(ObjsCt->ui_pan_name, LV_ALIGN_TOP_MID);
    lv_label_set_text(ObjsCt->ui_pan_name, "PAN");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ObjsCt->ui_pan_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ObjsCt->ui_pan_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_name, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // PAN args - 使用三个独立的label显示L C R
    // 隐藏原来的ui_pan_args
    ObjsCt->ui_pan_args = lv_label_create(ObjsCt->ui_pan_panel);
    lv_obj_add_flag(ObjsCt->ui_pan_args, LV_OBJ_FLAG_HIDDEN);  // 隐藏不用
    
    // 创建 L label
    ObjsCt->ui_pan_label_L = lv_label_create(ObjsCt->ui_pan_panel);
    lv_label_set_text(ObjsCt->ui_pan_label_L, "L");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_label_L, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ObjsCt->ui_pan_label_L, 55, 31);  // 左侧位置
    
    // 创建 R label
    ObjsCt->ui_pan_label_R = lv_label_create(ObjsCt->ui_pan_panel);
    lv_label_set_text(ObjsCt->ui_pan_label_R, "R");
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ObjsCt->ui_pan_label_R, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(ObjsCt->ui_pan_label_R, 130, 31);  // 右侧位置
    
    // 应用持久参数到UI
    ui_page_aux1_gain_arg_refresh(ArgsCt.gain_args);
    ui_page_aux1_fx_arg_refresh(ArgsCt.fx_args);
    ui_page_aux1_hi_arg_refresh(ArgsCt.hi_args);
    ui_page_aux1_mid_arg_refresh(ArgsCt.mid_args);
    ui_page_aux1_low_arg_refresh(ArgsCt.low_args);
    ui_page_aux1_hpf_arg_refresh(ArgsCt.hpf_args);
    ui_page_aux1_pan_arg_refresh(ArgsCt.pan_args);  // 初始化PAN颜色

    // 设置焦点面板边框颜色
    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    switch(ArgsCt.focus_target)
    {
        case 0: lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 1: lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 2: lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 3: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 4: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 5: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        case 6: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        default: break;
    }

    // 根据编辑模式设置当前焦点参数的文本颜色
    if(ArgsCt.edit_mode)
    {
        lv_color_t text_color = lv_color_hex(0xFFA500);
        switch(ArgsCt.focus_target)
        {
            case 0: lv_obj_set_style_text_color(ObjsCt->ui_select_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 1: lv_obj_set_style_text_color(ObjsCt->ui_gain_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 2: lv_obj_set_style_text_color(ObjsCt->ui_fx_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 3: lv_obj_set_style_text_color(ObjsCt->ui_pan_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 4: lv_obj_set_style_text_color(ObjsCt->ui_hi_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 5: lv_obj_set_style_text_color(ObjsCt->ui_mid_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 6: lv_obj_set_style_text_color(ObjsCt->ui_low_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            default: break;
        }
    }
}

void ui_page_Aux1_start(void)
{
    if(ObjsCt == NULL) return;  // 安全检查    
    ArgsCt.focus_target = 0;
    ArgsCt.edit_mode = 0;

    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ObjsCt->ui_select_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_gain_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_fx_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_pan_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_hi_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_mid_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_low_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_page_Aux1_exit(uint8_t del)
{
    if(del)
    {

    }
    else
    {

    }
    SendBuf[9] = 0x00;//退出当前页面，让从机关闭LED灯
    MasterSendExample(0x24);
}

void ui_page_Aux1_clean(void)
{
    lv_mem_free(ObjsCt);
    ObjsCt = NULL;
}

void ui_page_Aux1_request(uint32_t delay)
{
    switch(ui_pmanagerCt.id_tar)
    {
        //当前界面
        case UI_PAGE_SEL_3:
            break;
        //删除后台
        default:
            ui_pmanager_switch(UI_PAGE_SEL_3, delay, true);
            break;
    }
    SendBuf[9] = 0x01;//0 不是当前页面，1 是当前页面
    MasterSendExample(0x24);
}

// 参数表格定义（与ui_page_mic1保持一致）
// GAIN: 0db到30db (31个参数)
static const char *gain_args_table[] = {
    "0db", "+1db", "+2db", "+3db", "+4db", "+5db", "+6db", "+7db",
    "+8db", "+9db", "+10db", "+11db", "+12db", "+13db", "+14db", "+15db",
    "+16db", "+17db", "+18db", "+19db", "+20db", "+21db", "+22db", "+23db",
    "+24db", "+25db", "+26db", "+27db", "+28db", "+29db", "+30db"
};

// FX VOL: 0-10db (11个参数)
static const char *fx_args_table[] = {
    "0db", "+1db", "+2db", "+3db", "+4db", "+5db",
    "+6db", "+7db", "+8db", "+9db", "+10db"
};

// HI/MID/LOW: -15db到15db (31个参数)
static const char *eq_args_table[] = {
    "-15db", "-14db", "-13db", "-12db", "-11db", "-10db", "-9db", "-8db",
    "-7db", "-6db", "-5db", "-4db", "-3db", "-2db", "-1db", "0db",
    "+1db", "+2db", "+3db", "+4db", "+5db", "+6db", "+7db", "+8db",
    "+9db", "+10db", "+11db", "+12db", "+13db", "+14db", "+15db"
};

// MIC HPF: 80Hz/120Hz/200Hz (3个参数)
static const char *hpf_args_table[] = {
    "80Hz", "120Hz", "200Hz"
};

// 参数刷新函数
void ui_page_aux1_gain_arg_refresh(uint8_t argVal)
{
    ArgsCt.gain_args = argVal;
    lv_label_set_text(ObjsCt->ui_gain_args, gain_args_table[argVal]);
}

void ui_page_aux1_fx_arg_refresh(uint8_t argVal)
{
    ArgsCt.fx_args = argVal;
    lv_label_set_text(ObjsCt->ui_fx_args, fx_args_table[argVal]);
}

void ui_page_aux1_hi_arg_refresh(uint8_t argVal)
{
    ArgsCt.hi_args = argVal;
    lv_label_set_text(ObjsCt->ui_hi_args, eq_args_table[argVal]);
}

void ui_page_aux1_mid_arg_refresh(uint8_t argVal)
{
    ArgsCt.mid_args = argVal;
    lv_label_set_text(ObjsCt->ui_mid_args, eq_args_table[argVal]);
}

void ui_page_aux1_low_arg_refresh(uint8_t argVal)
{
    ArgsCt.low_args = argVal;
    lv_label_set_text(ObjsCt->ui_low_args, eq_args_table[argVal]);
}

void ui_page_aux1_hpf_arg_refresh(uint8_t argVal)
{
    ArgsCt.hpf_args = argVal;
    lv_label_set_text(ObjsCt->ui_pan_args, hpf_args_table[argVal]);
}

/*
    参数更新 - PAN
    @argVal     参数的值
*/
void ui_page_aux1_pan_arg_refresh(uint8_t argVal)
{
    ArgsCt.pan_args = argVal;
    
    // 所有label默认白色
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 根据选中值设置对应label为橙色
    switch(argVal)
    {
        case 0: // 不选（都是橙色）
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 1: // 选中L
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_L, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
        case 2: // 选中R
            lv_obj_set_style_text_color(ObjsCt->ui_pan_label_R, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
            break;
    }
}

// 编码器上键 - 焦点上移或参数增加
void ui_page_Aux1_encoder_up(void)
{
    if(ObjsCt == NULL) return;  // 安全检查
    
    if(ArgsCt.edit_mode == 0)
    {
        // 焦点模式：向上移动焦点
        if(ArgsCt.focus_target > 0)
        {
            ArgsCt.focus_target--;
        }
        else
        {
            ArgsCt.focus_target = 6; // 回到最后一个panel
        }

        // 更新所有panel边框为白色
        lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        // 设置当前焦点panel为绿色
        switch(ArgsCt.focus_target)
        {
            case 0: lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 1: lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 2: lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 3: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 4: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 5: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 6: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        }
    }
    else
    {
        // 编辑模式：参数增加
        switch(ArgsCt.focus_target)
        {
            case 0: // SELECTS - 不可编辑
                break;
            case 1: // GAIN: -10db到10db (0-20)
                if(ArgsCt.gain_args < sizeof(gain_args_table)/sizeof(gain_args_table[0]) - 1) {
                    ArgsCt.gain_args++;
                    ui_page_aux1_gain_arg_refresh(ArgsCt.gain_args);
                    SendBuf[0] = ArgsCt.gain_args;
                }
                break;
            case 2: // FX VOL: -10到10 (0-20)
                if(ArgsCt.fx_args < sizeof(fx_args_table)/sizeof(fx_args_table[0]) - 1) {
                    ArgsCt.fx_args++;
                    ui_page_aux1_fx_arg_refresh(ArgsCt.fx_args);
                    SendBuf[2] = ArgsCt.fx_args;
                }
                break;
            case 3: // PAN (L/C/R): 0-2
                if(ArgsCt.pan_args < 2) {  // 0=L, 1=C, 2=R
                    ArgsCt.pan_args++;
                    ui_page_aux1_pan_arg_refresh(ArgsCt.pan_args);
                    SendBuf[8] = ArgsCt.pan_args;
                }
                break;
            case 4: // HI: -15db到15db (0-30)
                if(ArgsCt.hi_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1) {
                    ArgsCt.hi_args++;
                    ui_page_aux1_hi_arg_refresh(ArgsCt.hi_args);
                    SendBuf[4] = ArgsCt.hi_args;
                }
                break;
            case 5: // MID: -15db到15db (0-30)
                if(ArgsCt.mid_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1) {
                    ArgsCt.mid_args++;
                    ui_page_aux1_mid_arg_refresh(ArgsCt.mid_args);
                    SendBuf[5] = ArgsCt.mid_args;
                }
                break;
            case 6: // LOW: -15db到15db (0-30)
                if(ArgsCt.low_args < sizeof(eq_args_table)/sizeof(eq_args_table[0]) - 1) {
                    ArgsCt.low_args++;
                    ui_page_aux1_low_arg_refresh(ArgsCt.low_args);
                    SendBuf[6] = ArgsCt.low_args;
                }
                break;
        }
        MasterSendExample(0x24);
    }
}

// 编码器下键 - 焦点下移或参数减少
void ui_page_Aux1_encoder_down(void)
{
    if(ObjsCt == NULL) return;  // 安全检查
    
    if(ArgsCt.edit_mode == 0)
    {
        // 焦点模式：向下移动焦点
        if(ArgsCt.focus_target < 6)
        {
            ArgsCt.focus_target++;
        }
        else
        {
            ArgsCt.focus_target = 0; // 回到第一个panel
        }

        // 更新所有panel边框为白色
        lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

        // 设置当前焦点panel为绿色
        switch(ArgsCt.focus_target)
        {
            case 0: lv_obj_set_style_border_color(ObjsCt->ui_select_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 1: lv_obj_set_style_border_color(ObjsCt->ui_gain_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 2: lv_obj_set_style_border_color(ObjsCt->ui_fx_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 3: lv_obj_set_style_border_color(ObjsCt->ui_pan_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 4: lv_obj_set_style_border_color(ObjsCt->ui_hi_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 5: lv_obj_set_style_border_color(ObjsCt->ui_mid_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 6: lv_obj_set_style_border_color(ObjsCt->ui_low_panel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); break;
        }
    }
    else
    {
        // 编辑模式：参数减少
        switch(ArgsCt.focus_target)
        {
            case 0: // SELECTS - 不可编辑
                break;
            case 1: // GAIN: -10db到10db (0-20)
                if(ArgsCt.gain_args > 0) {
                    ArgsCt.gain_args--;
                    ui_page_aux1_gain_arg_refresh(ArgsCt.gain_args);
                    SendBuf[0] = ArgsCt.gain_args;
                }
                break;
            case 2: // FX VOL: -10到10 (0-20)
                if(ArgsCt.fx_args > 0) {
                    ArgsCt.fx_args--;
                    ui_page_aux1_fx_arg_refresh(ArgsCt.fx_args);
                    SendBuf[2] = ArgsCt.fx_args;
                }
                break;
            case 3: // PAN (L/C/R): 0-2
                if(ArgsCt.pan_args > 0) {  // 0=L, 1=C, 2=R
                    ArgsCt.pan_args--;
                    ui_page_aux1_pan_arg_refresh(ArgsCt.pan_args);
                    SendBuf[8] = ArgsCt.pan_args;
                }
                break;
            case 4: // HI: -15db到15db (0-30)
                if(ArgsCt.hi_args > 0) {
                    ArgsCt.hi_args--;
                    ui_page_aux1_hi_arg_refresh(ArgsCt.hi_args);
                    SendBuf[4] = ArgsCt.hi_args;
                }
                break;
            case 5: // MID: -15db到15db (0-30)
                if(ArgsCt.mid_args > 0) {
                    ArgsCt.mid_args--;
                    ui_page_aux1_mid_arg_refresh(ArgsCt.mid_args);
                    SendBuf[5] = ArgsCt.mid_args;
                }
                break;
            case 6: // LOW: -15db到15db (0-30)
                if(ArgsCt.low_args > 0) {
                    ArgsCt.low_args--;
                    ui_page_aux1_low_arg_refresh(ArgsCt.low_args);
                    SendBuf[6] = ArgsCt.low_args;
                }
                break;
        }
        MasterSendExample(0x24);
    }
}

// 编码器OK键 - 切换焦点模式与编辑模式
void ui_page_Aux1_encoder_ok(void)
{
    if(ObjsCt == NULL) return;  // 安全检查
    
    if(ArgsCt.focus_target == 0) {
        // SELECTS不可编辑
        return;
    }

    ArgsCt.edit_mode = !ArgsCt.edit_mode;

    // 更新所有label为白色
    
    lv_obj_set_style_text_color(ObjsCt->ui_select_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_gain_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_fx_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_pan_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_hi_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_mid_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ObjsCt->ui_low_args, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    if(ArgsCt.edit_mode)
    {
        // 进入编辑模式，当前焦点label变为橙色
        lv_color_t text_color = lv_color_hex(0xFFA500);
        switch(ArgsCt.focus_target)
        {
            case 0: lv_obj_set_style_text_color(ObjsCt->ui_select_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 1: lv_obj_set_style_text_color(ObjsCt->ui_gain_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 2: lv_obj_set_style_text_color(ObjsCt->ui_fx_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 3: lv_obj_set_style_text_color(ObjsCt->ui_pan_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 4: lv_obj_set_style_text_color(ObjsCt->ui_hi_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 5: lv_obj_set_style_text_color(ObjsCt->ui_mid_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
            case 6: lv_obj_set_style_text_color(ObjsCt->ui_low_args, text_color, LV_PART_MAIN | LV_STATE_DEFAULT); break;
        }
    }
}
