/*
 * @Author: wujunpeng
 * @Date: 2025-11-27 12:23:03
 * @LastEditors: Do not edit
 * @LastEditTime: 2026-02-03 18:10:28
 * @FilePath: \lvgl_digtial_v01\MVsB1_BT_Karaoke_SDK_v0.3.3\BT_Audio_APP\bt_audio_app_src\lvgl_apps\ui_page_aux1\ui_page_aux1.h
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PAGE_Aux1_H
#define UI_PAGE_Aux1_H

/*################################### include ###################################*/
#include "type.h"
#include "lvgl.h"

/*################################### define/enum ###################################*/

/*################################### typedef ###################################*/
typedef struct _Aux1ObjsContext_{
    lv_obj_t *Aux1_obj;
    lv_obj_t *ui_select_panel;
    lv_obj_t *ui_select_name;
    lv_obj_t *ui_select_args; 
    lv_obj_t *ui_gain_panel; 
    lv_obj_t *ui_gain_name; 
    lv_obj_t *ui_gain_args; 
    lv_obj_t *ui_fx_panel; 
    lv_obj_t *ui_fx_name; 
    lv_obj_t *ui_fx_args; 
    lv_obj_t *ui_hi_panel; 
    lv_obj_t *ui_hi_name;
    lv_obj_t *ui_hi_args;
    lv_obj_t *ui_mid_panel;
    lv_obj_t *ui_mid_name;
    lv_obj_t *ui_mid_args;
    lv_obj_t *ui_low_panel;
    lv_obj_t *ui_low_name;
    lv_obj_t *ui_low_args;
    lv_obj_t *ui_pan_panel;
    lv_obj_t *ui_pan_name;
    lv_obj_t *ui_pan_args;
    lv_obj_t *ui_pan_label_L;  // PAN的L字母
    lv_obj_t *ui_pan_label_R;  // PAN的R字母
} Aux1ObjsContext;

typedef struct _Aux1ArgsContext_
{
    uint8_t focus_target;
    uint8_t edit_mode;      // 编辑模式, 0=面板选择模式, 1=参数编辑模式
    uint8_t gain_args;
    uint8_t fx_args;
    uint8_t hi_args;
    uint8_t mid_args;
    uint8_t low_args;
    uint8_t hpf_args;       // MIC HPF参数: 0=80Hz, 1=120Hz, 2=200Hz
    uint8_t pan_args;       // PAN参数: 0=不选，1=L(橙色), 2=R(橙色)，显示"L  R"
} Aux1ArgsContext;

/*################################### 全局变量 ###################################*/

/*################################### 全局函数 ###################################*/
void ui_page_Aux1_init(lv_obj_t *screen);
void ui_page_Aux1_start(void);
void ui_page_Aux1_exit(uint8_t del);
void ui_page_Aux1_clean(void);
void ui_page_Aux1_request(uint32_t delay);

// 参数刷新函数
void ui_page_aux1_gain_arg_refresh(uint8_t argVal);
void ui_page_aux1_fx_arg_refresh(uint8_t argVal);
void ui_page_aux1_hi_arg_refresh(uint8_t argVal);
void ui_page_aux1_mid_arg_refresh(uint8_t argVal);
void ui_page_aux1_low_arg_refresh(uint8_t argVal);
void ui_page_aux1_pan_arg_refresh(uint8_t argVal);

// 编码器控制函数
void ui_page_Aux1_encoder_up(void);
void ui_page_Aux1_encoder_down(void);
void ui_page_Aux1_encoder_ok(void);

#endif
